# Spring Boot 应用配置文件

# 服务器配置
server:
  port: 8080  # 应用程序监听端口

# Spring 核心配置
spring:
  application:
    name: test-example  # 应用程序名称
  main:
    allow-bean-definition-overriding: true

# 日志配置（简化版）
logging:
  level:
    root: INFO
    com.example.test: INFO